// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace DoctorsWebApplication.Models;

[Table("AppointmentPayment")]
[Serializable]
[JsonObject(MemberSerialization = MemberSerialization.OptOut)]
public partial class AppointmentPayment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AppointmentPaymentId { get; set; }

    [Required]
    public int AppointmentId { get; set; }

    [Required]
    public int DoctorFeeId { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid rowguid { get; set; }

    [Column(TypeName = "datetime")]
    [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}")]
    [DataType(DataType.Date)]
    public DateTime PaymentDate { get; set; }

    [ForeignKey("AppointmentId")]
    [InverseProperty("AppointmentPayments")]
    public virtual Appointment Appointment { get; set; }

    [ForeignKey("DoctorFeeId")]
    [InverseProperty("AppointmentPayments")]
    public virtual DoctorFee DoctorFee { get; set; }
}