// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace DoctorsWebApplication.Models;

[Table("Appointment")]
[Serializable]
[JsonObject(MemberSerialization = MemberSerialization.OptOut)]
public partial class Appointment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int AppointmentId { get; set; }

    [Column(TypeName = "datetime")]
    [Required]
    public DateTime StartAppointment { get; set; }

    [Column(TypeName = "datetime")]
    [Required]
    public DateTime EndAppointment { get; set; }

    [Required]
    public int DoctorId { get; set; }

    [Required]
    public int PatientId { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid rowguid { get; set; }

    [Required]
    public int Room { get; set; }

    [Required]
    public int Floor { get; set; }

    [InverseProperty("Appointment")]
    public virtual ICollection<AppointmentPayment> AppointmentPayments { get; } = new List<AppointmentPayment>();

    [ForeignKey("DoctorId")]
    [InverseProperty("Appointments")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("Appointments")]
    public virtual Patient Patient { get; set; }
}