// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace DoctorsWebApplication.Models;

[Table("DoctorFee")]
[Serializable]
[JsonObject(MemberSerialization = MemberSerialization.OptOut)]
public partial class DoctorFee
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int DoctorFeeId { get; set; }

    [Required]
    public int FeeId { get; set; }

    [Required]
    public int DoctorId { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string CreatedBy { get; set; }
    
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid rowguid { get; set; }

    [InverseProperty("DoctorFee")]
    public virtual ICollection<AppointmentPayment> AppointmentPayments { get; } = new List<AppointmentPayment>();

    [ForeignKey("DoctorId")]
    [InverseProperty("DoctorFees")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("FeeId")]
    [InverseProperty("DoctorFees")]
    public virtual Fee Fee { get; set; }
}