// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DoctorsWebApplication.Models;

[Table("Drug")]
public partial class Drug
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int DrugId { get; set; }

    [Required]
    [StringLength(250)]
    public string CommonName { get; set; }

    [Required]
    [StringLength(250)]
    public string MedicalName { get; set; }

    public int QuantityInStock { get; set; }

    public int ReorderQuantity { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedDate { get; set; }

    [StringLength(250)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid rowguid { get; set; }

    [Column(TypeName = "money")]
    [Required]
    public decimal RetailPrice { get; set; }

    [Column(TypeName = "money")]
    [Required]
    public decimal WholeSalePrice { get; set; }

    [InverseProperty("Drug")]
    public virtual ICollection<DrugSupplier> DrugSuppliers { get; } = new List<DrugSupplier>();

    [InverseProperty("Drug")]
    public virtual ICollection<PrescribedDrug> PrescribedDrugs { get; } = new List<PrescribedDrug>();
}