// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DoctorsWebApplication.Models;

[Table("GPSurgery")]
public partial class GPSurgery
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int GPSurgeryId { get; set; }

    [Required]
    [StringLength(250)]
    public string SurgeryName { get; set; }

    [Column(TypeName = "datetime")]
    [DisplayFormat(DataFormatString ="{0:dd/MM/yyyy}")]
    [DataType(DataType.Date)]
    public DateTime StartConsultDate { get; set; }

    [Column(TypeName = "datetime")]
    [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}")]
    [DataType(DataType.Date)]
    public DateTime EndConsultDate { get; set; }

    public bool CurrentFlag { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid rowguid { get; set; }

    [InverseProperty("GPSurgery")]
    public virtual ICollection<Doctor> Doctors { get; } = new List<Doctor>();
}