// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DoctorsWebApplication.Models;

[Table("Patient")]
[Microsoft.EntityFrameworkCore.Index("PersonId", Name = "IX_Patient", IsUnique = true)]
public partial class Patient
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int PatientId { get; set; }

    [Required]
    public int PersonId { get; set; }

    [Required]
    [StringLength(50)]
    public string TagId { get; set; }

    [Required]
    public int Room { get; set; }

    [Required]
    public int Floor { get; set; }

    [Required]
    public int DoctorId { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime ModifiedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public DateTime CreatedDate { get; set; }

    [StringLength(256)]
    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public string CreatedBy { get; set; }

    [DatabaseGenerated(DatabaseGeneratedOption.Computed)]
    public Guid rowguid { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<Appointment> Appointments { get; } = new List<Appointment>();

    [ForeignKey("DoctorId")]
    [InverseProperty("Patients")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("PersonId")]
    [InverseProperty("Patient")]
    public virtual Person Person { get; set; }

    [InverseProperty("Patient")]
    public virtual ICollection<PrescribedDrug> PrescribedDrugs { get; } = new List<PrescribedDrug>();
}