// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace DoctorsWebApplication.Models;

[Table("PrescribedDrug")]
public partial class PrescribedDrug
{
    [Key]
    public int PrescribedDrugId { get; set; }

    public int DrugId { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ModifiedDate { get; set; }

    [Required]
    [StringLength(256)]
    public string ModifiedBy { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [Required]
    [StringLength(256)]
    public string CreatedBy { get; set; }

    public Guid rowguid { get; set; }

    [ForeignKey("DoctorId")]
    [InverseProperty("PrescribedDrugs")]
    public virtual Doctor Doctor { get; set; }

    [ForeignKey("DrugId")]
    [InverseProperty("PrescribedDrugs")]
    public virtual Drug Drug { get; set; }

    [ForeignKey("PatientId")]
    [InverseProperty("PrescribedDrugs")]
    public virtual Patient Patient { get; set; }
}